# Change these first
owner: mikechernev # Your GitHub username
repo: uptime-checks # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal Website
    url: https://www.mikechernev.com
  - name: Blog
    url: http://geekyplatypus.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime-checks
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Mike Chernev's Upptime instance"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/mikechernev/uptime-checks). Powered by [**Upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
